// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hangmanweb {
	
	
	public partial class Igra {
		
		protected System.Web.UI.WebControls.Label lblGlavna;
		
		protected System.Web.UI.WebControls.Panel panelDugmad;
	}
}
