// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hangmanweb {
	
	
	public partial class Igra {
		
		protected System.Web.UI.HtmlControls.HtmlForm frmIgra;
		
		protected System.Web.UI.WebControls.TextBox hidIme;
		
		protected System.Web.UI.WebControls.Image imgZivot1;
		
		protected System.Web.UI.WebControls.Image imgZivot3;
		
		protected System.Web.UI.WebControls.Image imgZivot2;
		
		protected System.Web.UI.WebControls.Image imgZivot4;
		
		protected System.Web.UI.WebControls.Image imgZivot5;
		
		protected System.Web.UI.WebControls.Image imgZivot6;
		
		protected System.Web.UI.WebControls.Label lblGlavna;
		
		protected System.Web.UI.WebControls.Panel panelDugmad;
	}
}
