// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hangmanweb {
	
	
	public partial class Rekordi {
		
		protected System.Web.UI.WebControls.DropDownList ddlBrojRekorda;
		
		protected System.Web.UI.WebControls.DropDownList ddlSortiranje;
		
		protected System.Web.UI.WebControls.Repeater repRekordi;
		
		protected System.Web.UI.WebControls.Label lblIme;
		
		protected System.Web.UI.WebControls.Label lblVreme;
		
		protected System.Web.UI.WebControls.Label lblBrojSlova;
	}
}
